modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/fzzyhmstrs/EMI_loot/issues"

[[mods]]
modId = "emi_loot"
version = "${version}"
displayName = "EMI Loot"
displayURL = "https://github.com/fzzyhmstrs/EMI_loot"
authors = "fzzyhmstrs, lxly9 (art), unilock (ports)"
description = '''Plugin for EMI that shows chest loot, block drops, mob drops, and gameplay loot like fishing.'''
logoFile = "icon.png"

[[mixins]]
config="emi_loot.mixins.json"

[[dependencies.emi_loot]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[20.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.emi_loot]]
modId = "minecraft"
type = "REQUIRED"
versionRange = "[1.20.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.emi_loot]]
modId="emi"
mandatory=true
versionRange="[1.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.emi_loot]]
modId="fzzy_config"
mandatory=true
versionRange="[0.4.1,)"
ordering="AFTER"
side="BOTH"
