modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"
issueTrackerURL = "https://github.com/fzzyhmstrs/EMI_loot/issues"

[[mods]]
modId = "emi_loot"
version = "${version}"
displayName = "EMI Loot"
displayURL = "https://github.com/fzzyhmstrs/EMI_loot"
authors = "fzzyhmstrs, lxly9 (art), unilock (ports)"
description = '''Plugin for EMI that shows chest loot, block drops, mob drops, and gameplay loot like fishing.'''
logoFile = "icon.png"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[mixins]]
config = "emi_loot.mixins.json"

[[dependencies.emi_loot]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.emi_loot]]
modId = "minecraft"
type = "REQUIRED"
versionRange = "[1.21,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.emi_loot]]
modId = "emi"
type = "REQUIRED"
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.emi_loot]]
modId = "fzzy_config"
type = "REQUIRED"
versionRange = "[0.4.1,)"
ordering = "AFTER"
side = "BOTH"
